// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.david.module.proto.helloworld;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 家乡
   * </pre>
   *
   * <code>string hometown = 2;</code>
   * @return The hometown.
   */
  java.lang.String getHometown();
  /**
   * <pre>
   * 家乡
   * </pre>
   *
   * <code>string hometown = 2;</code>
   * @return The bytes for hometown.
   */
  com.google.protobuf.ByteString
      getHometownBytes();
}
