version: '2.3'
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: david_mysql
    ports:
      - "3307:3306"
    mem_limit: 512m
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: local
       MYSQL_USER: root
       MYSQL_PASSWORD: root
  redis-server:
    restart: always
    image: redis:latest
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    ports:
      - "6380:6379"
    mem_limit: 96m 